imports:
  # Content
  # -> Hugolify content types and taxonomies available https://www.hugolify.io/docs/sections/

  # Core theme
  - path: github.com/hugolify/hugolify-theme-3  
  - path: github.com/hugolify/hugolify-theme
  - path: github.com/hugolify/hugolify-theme-posts-categories
  - path: github.com/hugolify/hugolify-theme-posts
  - path: github.com/hugolify/hugolify-theme-projects-tags
  - path: github.com/hugolify/hugolify-theme-projects


  # CMS
  - path: github.com/hugolify/hugolify-admin
